all:
  children:
    control:
      hosts:
        control:
    webservers:
      hosts:
        webserver-1:
        webserver-2:
    dbservers:
      hosts:
        database:
    loadbalancer:
      hosts:
        loadbalancer:
    queue:
      hosts:
        queue: